//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cameratest {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cameratest.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto hinzufügen.
        /// </summary>
        internal static string str_addPicture {
            get {
                return ResourceManager.GetString("str_addPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzername existiert bereits.
        /// </summary>
        internal static string str_alreadyExistingUserName {
            get {
                return ResourceManager.GetString("str_alreadyExistingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mc:breakdown.
        /// </summary>
        internal static string str_breakdown {
            get {
                return ResourceManager.GetString("str_breakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Ihrer Firma.
        /// </summary>
        internal static string str_companyName {
            get {
                return ResourceManager.GetString("str_companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihre Benutzerdaten ein.
        /// </summary>
        internal static string str_enterUserData {
            get {
                return ResourceManager.GetString("str_enterUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string str_error {
            get {
                return ResourceManager.GetString("str_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Häufig gestellte Fragen.
        /// </summary>
        internal static string str_faq {
            get {
                return ResourceManager.GetString("str_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie alle Felder aus.
        /// </summary>
        internal static string str_fillAll {
            get {
                return ResourceManager.GetString("str_fillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen.
        /// </summary>
        internal static string str_forgotPassword {
            get {
                return ResourceManager.GetString("str_forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihre Logindaten ein.
        /// </summary>
        internal static string str_login {
            get {
                return ResourceManager.GetString("str_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maschinennummer.
        /// </summary>
        internal static string str_machineNumber {
            get {
                return ResourceManager.GetString("str_machineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Vorname.
        /// </summary>
        internal static string str_name {
            get {
                return ResourceManager.GetString("str_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Verbindung zum Server.
        /// </summary>
        internal static string str_noConnection {
            get {
                return ResourceManager.GetString("str_noConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Passwörter stimmen nicht überein.
        /// </summary>
        internal static string str_nonMatchingPasswords {
            get {
                return ResourceManager.GetString("str_nonMatchingPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht registrierte Benutzerdaten.
        /// </summary>
        internal static string str_notRegistered {
            get {
                return ResourceManager.GetString("str_notRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich.
        /// </summary>
        internal static string str_onSuccess {
            get {
                return ResourceManager.GetString("str_onSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andere.
        /// </summary>
        internal static string str_other {
            get {
                return ResourceManager.GetString("str_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string str_password {
            get {
                return ResourceManager.GetString("str_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort wiederholen.
        /// </summary>
        internal static string str_passwordAgain {
            get {
                return ResourceManager.GetString("str_passwordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer.
        /// </summary>
        internal static string str_phoneNumber {
            get {
                return ResourceManager.GetString("str_phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problembeschreibung.
        /// </summary>
        internal static string str_problemDescription {
            get {
                return ResourceManager.GetString("str_problemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frage.
        /// </summary>
        internal static string str_question {
            get {
                return ResourceManager.GetString("str_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrierung.
        /// </summary>
        internal static string str_register {
            get {
                return ResourceManager.GetString("str_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Registrierung war erfolgreich, Sie können sich jetzt einloggen.
        /// </summary>
        internal static string str_registerSuccess {
            get {
                return ResourceManager.GetString("str_registerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einen Fehler melden.
        /// </summary>
        internal static string str_reportBug {
            get {
                return ResourceManager.GetString("str_reportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senden.
        /// </summary>
        internal static string str_send {
            get {
                return ResourceManager.GetString("str_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art des Problems.
        /// </summary>
        internal static string str_sortOfProblem {
            get {
                return ResourceManager.GetString("str_sortOfProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ersatzteile.
        /// </summary>
        internal static string str_spareParts {
            get {
                return ResourceManager.GetString("str_spareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art der Maschine.
        /// </summary>
        internal static string str_typeOfMachine {
            get {
                return ResourceManager.GetString("str_typeOfMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine gültige E-Mail Adresse an.
        /// </summary>
        internal static string str_validMailAdress {
            get {
                return ResourceManager.GetString("str_validMailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos zur Problembehandlung.
        /// </summary>
        internal static string str_videos {
            get {
                return ResourceManager.GetString("str_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzername oder das Passwort ist falsch.
        /// </summary>
        internal static string str_wrongUserNameOrPassword {
            get {
                return ResourceManager.GetString("str_wrongUserNameOrPassword", resourceCulture);
            }
        }
    }
}
